version: "3.8"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: maria
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - '3306:3306'
    volumes:
      - ./Code Academy 2017/2. Bases de données/2. MariaDB pour bien commencer:/docker-entrypoint-initdb.d/
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
